# Site settings
title: Programaci칩n y m치s
description: 'Aprende a programar desde cero, y desarrolla sitios web y aplicaciones m칩viles. Tutoriales sobre HTML5, CSS3, Javascript, PHP, Laravel, MySQL, Android y m치s.'
url: 'https://programacionymas.com'
baseurl: '/'
google_analytics: 'UA-26345705-3'
disqus_shortname: 'jcarlosr'

author:
  name: 'Juan Ramos'
  email: juancagb.17@gmail.com
  google_username: SorcJC
  youtube_username: SorcJC
  twitter_username: programacionym
  facebook_username: programacionymas
  github_username:  JCarlosR
  linkedin_username:  jcarlos17

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 5
paginate_path: /blog/page/:num/
permalink: /blog/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
